// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductTests.Infrastructure;

#nullable disable

namespace ProductTests.Infrastructure.Migrations
{
    [DbContext(typeof(ProductTestDbContext))]
    [Migration("20220605120657_testrun")]
    partial class testrun
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("producttest")
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("EntityFrameworkHiLoSequence")
                .IncrementsBy(10);

            modelBuilder.Entity("ProductTests.Domain.Model.TestCaseAggregate.TestCase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Preconditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestCases", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestCaseAggregate.TestStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("StepNo")
                        .HasColumnType("bigint");

                    b.Property<long>("TestCaseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestSteps", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestPlanAggregate.TestPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProductDocumentationId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SprintId")
                        .HasColumnType("bigint");

                    b.Property<int>("TestType")
                        .HasColumnType("int");

                    b.Property<long?>("WorkItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TestPlans", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestPlanAggregate.TestSuite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrderNo")
                        .HasColumnType("bigint");

                    b.Property<long>("TestPlanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestPlanId");

                    b.ToTable("TestSuites", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestPlanAggregate.TestSuiteTestCaseMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TestCaseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestSuiteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("TestSuiteId");

                    b.ToTable("TestSuiteTestCaseMappings", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestCaseVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Preconditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResultStatus")
                        .HasColumnType("int");

                    b.Property<long?>("TestSuiteVersionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestSuiteVersionId");

                    b.ToTable("TestCasesVersion", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestPlanVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProductDocumentationId")
                        .HasColumnType("bigint");

                    b.Property<int>("TestType")
                        .HasColumnType("int");

                    b.Property<long?>("WorkItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TestPlansVersion", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("RunningStatus")
                        .HasColumnType("int");

                    b.Property<long?>("SprintId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestPlanId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestPlanVersionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestPlanVersionId");

                    b.ToTable("TestRuns", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestStepVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResultStatus")
                        .HasColumnType("int");

                    b.Property<long>("StepNo")
                        .HasColumnType("bigint");

                    b.Property<long>("TestCaseVersionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseVersionId");

                    b.ToTable("TestStepsVersion", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestSuiteVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TestPlanVersionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestPlanVersionId");

                    b.ToTable("TestSuitesVersion", "producttest");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestCaseAggregate.TestStep", b =>
                {
                    b.HasOne("ProductTests.Domain.Model.TestCaseAggregate.TestCase", "TestCase")
                        .WithMany("TestSteps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestPlanAggregate.TestSuite", b =>
                {
                    b.HasOne("ProductTests.Domain.Model.TestPlanAggregate.TestPlan", "TestPlan")
                        .WithMany("TestSuites")
                        .HasForeignKey("TestPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestPlan");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestPlanAggregate.TestSuiteTestCaseMapping", b =>
                {
                    b.HasOne("ProductTests.Domain.Model.TestCaseAggregate.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId");

                    b.HasOne("ProductTests.Domain.Model.TestPlanAggregate.TestSuite", "TestSuite")
                        .WithMany("TestSuiteTestCaseMappings")
                        .HasForeignKey("TestSuiteId");

                    b.Navigation("TestCase");

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestCaseVersion", b =>
                {
                    b.HasOne("ProductTests.Domain.Model.TestRunAggregate.TestSuiteVersion", null)
                        .WithMany("TestCaseVersions")
                        .HasForeignKey("TestSuiteVersionId");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestRun", b =>
                {
                    b.HasOne("ProductTests.Domain.Model.TestRunAggregate.TestPlanVersion", "TestPlanVersion")
                        .WithMany()
                        .HasForeignKey("TestPlanVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestPlanVersion");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestStepVersion", b =>
                {
                    b.HasOne("ProductTests.Domain.Model.TestRunAggregate.TestCaseVersion", "TestCaseVersion")
                        .WithMany("TestStepsVersion")
                        .HasForeignKey("TestCaseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCaseVersion");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestSuiteVersion", b =>
                {
                    b.HasOne("ProductTests.Domain.Model.TestRunAggregate.TestPlanVersion", "TestPlanVersion")
                        .WithMany("TestSuitesVersion")
                        .HasForeignKey("TestPlanVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestPlanVersion");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestCaseAggregate.TestCase", b =>
                {
                    b.Navigation("TestSteps");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestPlanAggregate.TestPlan", b =>
                {
                    b.Navigation("TestSuites");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestPlanAggregate.TestSuite", b =>
                {
                    b.Navigation("TestSuiteTestCaseMappings");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestCaseVersion", b =>
                {
                    b.Navigation("TestStepsVersion");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestPlanVersion", b =>
                {
                    b.Navigation("TestSuitesVersion");
                });

            modelBuilder.Entity("ProductTests.Domain.Model.TestRunAggregate.TestSuiteVersion", b =>
                {
                    b.Navigation("TestCaseVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
